# Generated by Django 2.1.7 on 2021-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pic',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
    ]
